FROM netlify/build:8fe1bb2e99ea860d37d734aa796a72347aa56ce7

ENV NETLIFY_REPO_URL="/opt/repo"
ENV NETLIFY_BUILD_BASE="/opt/buildhome"
ENV NETLIFY_REPO_DIR="$NETLIFY_BUILD_BASE/repo"

WORKDIR $NETLIFY_REPO_URL
COPY ./ ./
RUN mkdir -p $NETLIFY_REPO_DIR
RUN cp -p -r $NETLIFY_REPO_URL/* $NETLIFY_REPO_DIR/
RUN build ./scripts/netlify.sh
